name: smarttasks
description: SmartTasks Flutter client (scaffold)
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  dio: ^5.2.1
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  sembast: ^5.0.0
  path_provider: ^2.0.14
  firebase_core: ^2.12.0
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true