apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarttasks-backend
  labels:
    app: smarttasks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smarttasks
  template:
    metadata:
      labels:
        app: smarttasks
    spec:
      containers:
      - name: backend
        image: your-docker-repo/smarttasks-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: smarttasks.settings
        - name: DATABASE_URL
          value: postgres://user:password@postgres:5432/smarttasks
        - name: REDIS_URL
          value: redis://redis:6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: smarttasks-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: smarttasks